spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/instagram_kpi}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

instagram:
  api:
    key: ${INSTAGRAM_API_KEY:your_api_key_here}
    username: ${INSTAGRAM_USERNAME:your_username}
    password: ${INSTAGRAM_PASSWORD:your_password}

logging:
  level:
    root: INFO
    com.instagram.kpi: DEBUG 