spring:
  datasource:
    url: jdbc:h2:mem:instagramdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  websocket:
    allowed-origins: http://localhost:3000

server:
  port: 8080
  servlet:
    context-path:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

logging:
  level:
    root: INFO
    com.instagram.kpi: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 

instagram:
  api:
    graph-api-version: v23.0
    access-token: ${INSTAGRAM_USER_ACCESS_TOKEN}
    business-account-id: ${INSTAGRAM_BUSINESS_ACCOUNT_ID}

facebook:
  app-id: ${FACEBOOK_APP_ID}
  app-secret: ${FACEBOOK_APP_SECRET}
  short-lived-token: ${FACEBOOK_SHORT_LIVED_TOKEN}